fix: default_database in the config has been deprecated since 0.12
ErrorException: User Deprecated: default_database in the config has been deprecated since 0.12, use default_environment instead.
  File "/var/www/geokrety/vendor/robmorgan/phinx/src/Phinx/Config/Config.php", line 223, in Phinx\Config\Config::getDefaultEnvironment
    trigger_error('default_database in the config has been deprecated since 0.12, use default_environment instead.', E_USER_DEPRECATED);
  File "/var/www/geokrety/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php", line 73, in Phinx\Console\Command\Migrate::execute
    $environment = $this->getConfig()->getDefaultEnvironment();
  File "/var/www/geokrety/vendor/symfony/console/Command/Command.php", line 298, in Symfony\Component\Console\Command\Command::run
    $statusCode = $this->execute($input, $output);
  File "/var/www/geokrety/vendor/symfony/console/Application.php", line 1040, in Symfony\Component\Console\Application::doRunCommand
    return $command->run($input, $output);
  File "/var/www/geokrety/vendor/symfony/console/Application.php", line 301, in Symfony\Component\Console\Application::doRun
    $exitCode = $this->doRunCommand($command, $input, $output);
...
(4 additional frame(s) were not displayed)